project_id = "igrtzfvphltnoiwedbtz"

[functions.sitemap-xml]
verify_jwt = false

[functions.sitemap-index]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.upload-to-ftp]
verify_jwt = false